config/routes.rb
Rails.application.routes.draw do

  namespace :accounting do
  end
  namespace :accounting do
  end
  namespace :accounting do
    resources :accounts
    resources :transactions
    resources :events
    resources :entry_lines, only: [:index, :show]
    resources :entries, only: [:index, :show]


    
  end
  get '/accounting', to: 'accounting#show'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  root 'pages#home'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  } 
  resources :users, only: [:index, :edit, :update, :delete]

  get 'profile', action: :show, controller: 'users'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/accounting/event.rb
class Accounting::Event < ApplicationRecord
  has_many :transactions
  def status
    case true
    when (self.start_date .. self.end_date).cover?(Date.today)
      'active'
    when Date.today < self.start_date
      'next'
    when Date.today > self.end_date
      'past'
    end
    
  end

end

app/controllers/accounting/events_controller.rb
class Accounting::EventsController < ApplicationController
  before_action :set_accounting_event, only: [:show, :edit, :update, :destroy]
  before_action :set_dashboard, only: [:show, :new, :edit, :index]
  layout "dashboard"
  # GET /accounting/events
  # GET /accounting/events.json
  def index
    @accounting_events = Accounting::Event.all
    authorize Accounting::Event
  end

  # GET /accounting/events/1
  # GET /accounting/events/1.json
  def show
    authorize Accounting::Event

  end

  # GET /accounting/events/new
  def new
    @accounting_event = Accounting::Event.new
    authorize Accounting::Event

  end

  # GET /accounting/events/1/edit
  def edit
    authorize Accounting::Event

  end

  # POST /accounting/events
  # POST /accounting/events.json
  def create
    @accounting_event = Accounting::Event.new(accounting_event_params)
    authorize Accounting::Event

    respond_to do |format|
      if @accounting_event.save
        format.html { redirect_to @accounting_event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @accounting_event }
      else
        format.html { render :new }
        format.json { render json: @accounting_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounting/events/1
  # PATCH/PUT /accounting/events/1.json
  def update
    authorize Accounting::Event
    respond_to do |format|
      if @accounting_event.update(accounting_event_params)
        format.html { redirect_to @accounting_event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @accounting_event }
      else
        format.html { render :edit }
        format.json { render json: @accounting_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounting/events/1
  # DELETE /accounting/events/1.json
  def destroy
    authorize Accounting::Event

    @accounting_event.destroy
    respond_to do |format|
      format.html { redirect_to accounting_events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accounting_event
      @accounting_event = Accounting::Event.find(params[:id])
    end

    def set_dashboard
      @dashboard = true
    end

    # Only allow a list of trusted parameters through.
    def accounting_event_params
      params.require(:accounting_event).permit(:name, :start_date, :end_date, :comments)
    end
end

app/helpers/accounting/events_helper.rb
module Accounting::EventsHelper
  def get_status_color(status)
    case status
    when 'active'
      'success'
    when 'past'
      'dark'
    else 'next'
      'warning'
    end
  end

  def get_status_icon(status)
    case status
    when 'active'
      'check'
    when 'past'
      'alt'
    else 'next'
      'plus'
    end
  end

end

app/views/accounting/events/index/_card.html.erb
<div class="col-lg-4 col-md-6 col-12 mt-2">
  <div class="card border-left-<%= get_status_color event.status %> shadow py-2">
    <div class="card-body">
      <h4 class="h6 font-weight-bold text-secondary text-uppercase mb-2"><%=  event.name %></h4>
      <hr class='m-0'>
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <p class='text-xs font-weight-bold text-info text-uppercase mb-0 mt-1'>Fecha de Inicio</p>
          <strong><%= event.start_date %></strong>
          <p class='text-xs font-weight-bold text-info text-uppercase mb-0 mt-1'>Fecha de Culminación</p>
          <strong><%= event.end_date %></strong>
        </div>
        <div class="col-auto d-flex flex-column justify-content-center align-items-center text-<%= get_status_color event.status %>">
          <i class="far fa-calendar-<%= get_status_icon event.status %> fa-3x"></i>
          <%= t(event.status) %>
        </div>
      </div>
      <p class='text-xs font-weight-bold text-info text-uppercase mb-0 mt-1'>Comentarios</p>
      <p><%= event.comments %></p>
      <p class='text-xs font-weight-bold text-info text-uppercase mb-0 mt-1'>Acciones</p>
      
      <%= link_to event, method: :delete, data: { confirm: 'Are you sure?' }, class:'float-right mr-1 text-danger' do %>
        <i class="far fa-trash-alt"></i>
      <% end %>
      <%= link_to edit_accounting_event_path(event), class:'float-right mr-1 text-info' do %>
        <i class="far fa-edit"></i>
      <% end %>
      <% if view == 'index' %>
        <%= link_to event, class:'float-right mr-1 text-success' do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% else %>
        <%= link_to accounting_events_path, class:'float-right mr-1 text-warning' do %>
          <i class="fas fa-undo"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>