config/routes.rb
Rails.application.routes.draw do

  namespace :accounting do
  end
  namespace :accounting do
  end
  namespace :accounting do
    resources :accounts
    resources :transactions
    resources :events
    resources :entry_lines, only: [:index, :show]
    resources :entries, only: [:index, :show]


    
  end
  get '/accounting', to: 'accounting#show'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  root 'pages#home'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  } 
  resources :users, only: [:index, :edit, :update, :delete]

  get 'profile', action: :show, controller: 'users'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/accounting/account.rb
class Accounting::Account < ApplicationRecord
  has_many :transactions

  after_create :create_initial_transaction

  def create_initial_transaction
    self.transactions.create(date: self.created_at, type_of_transaction: 2, amount: self.initial_balance.to_f, comments: 'New account!')
  end

  def balance 
    self.transactions.reduce(self.initial_balance.to_f) {|amount, num| num.try(:type_of_transaction) == 0 ? amount + num.amount : num.try(:type_of_transaction) == 1 ? amount - num.amount : amount + 0}
  end
end

app/controllers/accounting/accounts_controller.rb
class Accounting::AccountsController < ApplicationController
  before_action :set_accounting_account, only: [:show, :edit, :update, :destroy]
  before_action :set_dashboard, only: [:show, :new, :edit, :index]
  layout "dashboard"
  # GET /accounting/accounts
  # GET /accounting/accounts.json
  def index
    authorize Accounting::Account

    @accounting_accounts = Accounting::Account.all
  end

  # GET /accounting/accounts/1
  # GET /accounting/accounts/1.json
  def show
    authorize Accounting::Account

  end

  # GET /accounting/accounts/new
  def new
    
    @accounting_account = Accounting::Account.new
    authorize Accounting::Account

  end

  # GET /accounting/accounts/1/edit
  def edit
    authorize Accounting::Account
  end

  # POST /accounting/accounts
  # POST /accounting/accounts.json
  def create

    @accounting_account = Accounting::Account.new(accounting_account_params)
    authorize Accounting::Account
    respond_to do |format|
      if @accounting_account.save
        format.html { redirect_to @accounting_account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @accounting_account }
      else
        format.html { render :new }
        format.json { render json: @accounting_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounting/accounts/1
  # PATCH/PUT /accounting/accounts/1.json
  def update
    authorize Accounting::Account

    respond_to do |format|
      if @accounting_account.update(accounting_account_params)
        format.html { redirect_to @accounting_account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @accounting_account }
      else
        format.html { render :edit }
        format.json { render json: @accounting_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounting/accounts/1
  # DELETE /accounting/accounts/1.json
  def destroy
    authorize Accounting::Account

    @accounting_account.destroy
    respond_to do |format|
      format.html { redirect_to accounting_accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accounting_account
      @accounting_account = Accounting::Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def accounting_account_params
      params.require(:accounting_account).permit(:name, :initial_balance, :in_charge_id)
    end
end

app/helpers/accounting/accounts_helper.rb
module Accounting::AccountsHelper

  def get_balance_color(balance)
    case balance
    when -Float::INFINITY...0
      'danger'
    when 0
      'warning'
    else 
      'success'
    end
  end

  def get_balance_icon(balance)
    case balance
    when -Float::INFINITY...0
      'skull-crossbones'
    when 0
      'exclamation'
    else 
      'check'
    end
  end
end

app/views/accounting/accounts/index/_card.html.erb
<div class="col-lg-4 col-md-6 col-12 mt-2">
  <div class="card border-left-<%= get_balance_color account.balance %> shadow py-2">
    <div class="card-body">
      <h4 class="h6 font-weight-bold text-secondary text-uppercase mb-2"><%=  account.name %></h4>
      <hr class='m-0'>
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <p class='text-xs font-weight-bold text-info text-uppercase mb-0 mt-1'>Responsable</p>
          <strong><%= account.in_charge_id %></strong>
          <p class='text-xs font-weight-bold text-info text-uppercase mb-0 mt-1'>Número de Transacciones</p>
          <strong><%= account.transactions.count %></strong>
        </div>
        <div class="col-auto d-flex flex-column justify-content-center align-items-center text-<%= get_balance_color account.balance %>">
          <i class="fas fa-<%= get_balance_icon account.balance %> fa-2x"></i>
          <h6 class='text-xs font-weight-bold text-<%= get_balance_color account.balance %> text-uppercase mb-0 mt-1'>Balance</h6>
          <%= account.balance %>
        </div>
      </div>
      <p class='text-xs font-weight-bold text-info text-uppercase mb-0 mt-1'>Acciones</p>
      
      <%= link_to account, method: :delete, data: { confirm: 'Are you sure?' }, class:'float-right mr-1 text-danger' do %>
        <i class="far fa-trash-alt"></i>
      <% end %>
      <%= link_to edit_accounting_account_path(account), class:'float-right mr-1 text-info' do %>
        <i class="far fa-edit"></i>
      <% end %>
      <% if view == 'index' %>
        <%= link_to account, class:'float-right mr-1 text-success' do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% else %>
        <%= link_to accounting_accounts_path, class:'float-right mr-1 text-warning' do %>
          <i class="fas fa-undo"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>