config/routes.rb
Rails.application.routes.draw do

  namespace :accounting do
  end
  namespace :accounting do
  end
  namespace :accounting do
    resources :accounts
    resources :transactions
    resources :events
    resources :entry_lines, only: [:index, :show]
    resources :entries, only: [:index, :show]


    
  end
  get '/accounting', to: 'accounting#show'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  root 'pages#home'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  } 
  resources :users, only: [:index, :edit, :update, :delete]

  get 'profile', action: :show, controller: 'users'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/accounting.rb
module Accounting
  def self.table_name_prefix
    'accounting_'
  end
end

app/models/accounting/account.rb
class Accounting::Account < ApplicationRecord
  has_many :transactions

  after_create :create_initial_transaction

  def create_initial_transaction
    self.transactions.create(date: self.created_at, type_of_transaction: 2, amount: self.initial_balance.to_f, comments: 'New account!')
  end

  def balance 
    self.transactions.reduce(self.initial_balance.to_f) {|amount, num| num.try(:type_of_transaction) == 0 ? amount + num.amount : num.try(:type_of_transaction) == 1 ? amount - num.amount : amount + 0}
  end
end

app/models/accounting/entry.rb
class Accounting::Entry < ApplicationRecord
  belongs_to :movement, foreign_key: :transaction_id, class_name: 'Transaction'

  has_many :entry_lines

  after_create :create_lines

  def create_lines
    ## Select the type of transaction
    case self.movement.type_of_transaction
    when 0
      self.update(description: 'Sale')
      income = self.movement.amount*-1
      account = self.movement.amount
    when 1
      self.update(description: 'Purchase')
      outcome = self.movement.amount
      account = self.movement.amount*-1
    when 2
      self.update(description: 'New Account')
      account = self.movement.amount
      capital = self.movement.amount*-1
    when 3
      self.update(description: 'Destroy Account')
      account = self.movement.amount*-1
      capital = self.movement.amount
    end
    ## Make a hash to sort the lines
    lines = {
      'capital' => ['3001', capital],
      'account' => ["10#{self.movement.account.id}", account],
      'income' => ['4001', income],
      'outcome' => ['5001', outcome] 
    }.reject {|k, v| v[1].blank? or v[1] == 0}

    ## Create lines
    lines.each do |name, values|
      debit = values[1] > 0 ? values[1] : 0
      credit = values[1] < 0 ? values[1] : 0
      self.entry_lines.create(account_number: values[0], credit: credit, debit: debit)
    end
  end
end

app/models/accounting/entry_line.rb
class Accounting::EntryLine < ApplicationRecord
  belongs_to :entry, foreign_key: :entry_id

end

app/models/accounting/event.rb
class Accounting::Event < ApplicationRecord
  has_many :transactions
  def status
    case true
    when (self.start_date .. self.end_date).cover?(Date.today)
      'active'
    when Date.today < self.start_date
      'next'
    when Date.today > self.end_date
      'past'
    end
    
  end

end

app/models/accounting/transaction.rb
class Accounting::Transaction < ApplicationRecord
  belongs_to :event, foreign_key: :event_id, optional: true
  belongs_to :account, foreign_key: :account_id

  has_one :entry

  after_create :make_entry

  def make_entry
    self.create_entry(date: self.date)
  end
end

app/controllers/accounting/accounts_controller.rb
class Accounting::AccountsController < ApplicationController
  before_action :set_accounting_account, only: [:show, :edit, :update, :destroy]
  before_action :set_dashboard, only: [:show, :new, :edit, :index]
  layout "dashboard"
  # GET /accounting/accounts
  # GET /accounting/accounts.json
  def index
    authorize Accounting::Account

    @accounting_accounts = Accounting::Account.all
  end

  # GET /accounting/accounts/1
  # GET /accounting/accounts/1.json
  def show
    authorize Accounting::Account

  end

  # GET /accounting/accounts/new
  def new
    
    @accounting_account = Accounting::Account.new
    authorize Accounting::Account

  end

  # GET /accounting/accounts/1/edit
  def edit
    authorize Accounting::Account
  end

  # POST /accounting/accounts
  # POST /accounting/accounts.json
  def create

    @accounting_account = Accounting::Account.new(accounting_account_params)
    authorize Accounting::Account
    respond_to do |format|
      if @accounting_account.save
        format.html { redirect_to @accounting_account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @accounting_account }
      else
        format.html { render :new }
        format.json { render json: @accounting_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounting/accounts/1
  # PATCH/PUT /accounting/accounts/1.json
  def update
    authorize Accounting::Account

    respond_to do |format|
      if @accounting_account.update(accounting_account_params)
        format.html { redirect_to @accounting_account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @accounting_account }
      else
        format.html { render :edit }
        format.json { render json: @accounting_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounting/accounts/1
  # DELETE /accounting/accounts/1.json
  def destroy
    authorize Accounting::Account

    @accounting_account.destroy
    respond_to do |format|
      format.html { redirect_to accounting_accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accounting_account
      @accounting_account = Accounting::Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def accounting_account_params
      params.require(:accounting_account).permit(:name, :initial_balance, :in_charge_id)
    end
end

app/controllers/accounting/entries_controller.rb
class Accounting::EntriesController < ApplicationController
  before_action :set_accounting_entry, only: [:show]
  before_action :set_dashboard, only: [:show, :index]
  layout "dashboard"
  # GET /accounting/entries
  # GET /accounting/entries.json
  def index
    @accounting_entries = Accounting::Entry.all
  end

  # GET /accounting/entries/1
  # GET /accounting/entries/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accounting_entry
      @accounting_entry = Accounting::Entry.find(params[:id])
    end
    def set_dashboard
      @dashboard = true
    end
end

app/controllers/accounting/entry_lines_controller.rb
class Accounting::EntryLinesController < ApplicationController
  before_action :set_accounting_entry_line, only: [:show]
  before_action :set_dashboard, only: [:show, :index]
  layout "dashboard"
  # GET /accounting/entry_lines
  # GET /accounting/entry_lines.json
  def index
    @accounting_entry_lines = Accounting::EntryLine.all
  end

  # GET /accounting/entry_lines/1
  # GET /accounting/entry_lines/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accounting_entry_line
      @accounting_entry_line = Accounting::EntryLine.find(params[:id])
    end
    def set_dashboard
      @dashboard = true
    end
end

app/controllers/accounting/events_controller.rb
class Accounting::EventsController < ApplicationController
  before_action :set_accounting_event, only: [:show, :edit, :update, :destroy]
  before_action :set_dashboard, only: [:show, :new, :edit, :index]
  layout "dashboard"
  # GET /accounting/events
  # GET /accounting/events.json
  def index
    @accounting_events = Accounting::Event.all
    authorize Accounting::Event
  end

  # GET /accounting/events/1
  # GET /accounting/events/1.json
  def show
    authorize Accounting::Event

  end

  # GET /accounting/events/new
  def new
    @accounting_event = Accounting::Event.new
    authorize Accounting::Event

  end

  # GET /accounting/events/1/edit
  def edit
    authorize Accounting::Event

  end

  # POST /accounting/events
  # POST /accounting/events.json
  def create
    @accounting_event = Accounting::Event.new(accounting_event_params)
    authorize Accounting::Event

    respond_to do |format|
      if @accounting_event.save
        format.html { redirect_to @accounting_event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @accounting_event }
      else
        format.html { render :new }
        format.json { render json: @accounting_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounting/events/1
  # PATCH/PUT /accounting/events/1.json
  def update
    authorize Accounting::Event
    respond_to do |format|
      if @accounting_event.update(accounting_event_params)
        format.html { redirect_to @accounting_event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @accounting_event }
      else
        format.html { render :edit }
        format.json { render json: @accounting_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounting/events/1
  # DELETE /accounting/events/1.json
  def destroy
    authorize Accounting::Event

    @accounting_event.destroy
    respond_to do |format|
      format.html { redirect_to accounting_events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accounting_event
      @accounting_event = Accounting::Event.find(params[:id])
    end

    def set_dashboard
      @dashboard = true
    end

    # Only allow a list of trusted parameters through.
    def accounting_event_params
      params.require(:accounting_event).permit(:name, :start_date, :end_date, :comments)
    end
end

app/controllers/accounting/transactions_controller.rb
class Accounting::TransactionsController < ApplicationController
  before_action :set_accounting_transaction, only: [:show, :edit, :update, :destroy]
  before_action :set_dashboard, only: [:show, :new, :edit, :index]
  layout "dashboard"
  # GET /accounting/transactions
  # GET /accounting/transactions.json
  def index
    @accounting_transactions = Accounting::Transaction.all
    authorize Accounting::Transaction
  end

  # GET /accounting/transactions/1
  # GET /accounting/transactions/1.json
  def show
    authorize Accounting::Transaction
  end

  # GET /accounting/transactions/new
  def new
    @accounting_transaction = Accounting::Transaction.new
    authorize Accounting::Transaction
  end

  # GET /accounting/transactions/1/edit
  def edit
    authorize Accounting::Transaction
  end

  # POST /accounting/transactions
  # POST /accounting/transactions.json
  def create
    @accounting_transaction = Accounting::Transaction.new(accounting_transaction_params)
    authorize Accounting::Transaction

    respond_to do |format|
      if @accounting_transaction.save
        format.html { redirect_to @accounting_transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @accounting_transaction }
      else
        format.html { render :new }
        format.json { render json: @accounting_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounting/transactions/1
  # PATCH/PUT /accounting/transactions/1.json
  def update
    authorize Accounting::Transaction

    respond_to do |format|
      if @accounting_transaction.update(accounting_transaction_params)
        format.html { redirect_to @accounting_transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @accounting_transaction }
      else
        format.html { render :edit }
        format.json { render json: @accounting_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounting/transactions/1
  # DELETE /accounting/transactions/1.json
  def destroy
    authorize Accounting::Transaction

    @accounting_transaction.destroy
    respond_to do |format|
      format.html { redirect_to accounting_transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accounting_transaction
      @accounting_transaction = Accounting::Transaction.find(params[:id])
    end
    
    def set_dashboard
      @dashboard = true
    end

    # Only allow a list of trusted parameters through.
    def accounting_transaction_params
      params.require(:accounting_transaction).permit(:event_id, :date, :type_of_transaction, :comments, :amount, :account_id)
    end
end

app/controllers/accounting_controller.rb
class AccountingController < ApplicationController
  def show

    respond_to do |f|
      f.html {render 'pages/accounting'}
    end
  end
end

app/helpers/accounting/accounts_helper.rb
module Accounting::AccountsHelper

  def get_balance_color(balance)
    case balance
    when -Float::INFINITY...0
      'danger'
    when 0
      'warning'
    else 
      'success'
    end
  end

  def get_balance_icon(balance)
    case balance
    when -Float::INFINITY...0
      'skull-crossbones'
    when 0
      'exclamation'
    else 
      'check'
    end
  end
end

app/helpers/accounting/entries_helper.rb
module Accounting::EntriesHelper
end

app/helpers/accounting/entry_lines_helper.rb
module Accounting::EntryLinesHelper
end

app/helpers/accounting/events_helper.rb
module Accounting::EventsHelper
  def get_status_color(status)
    case status
    when 'active'
      'success'
    when 'past'
      'dark'
    else 'next'
      'warning'
    end
  end

  def get_status_icon(status)
    case status
    when 'active'
      'check'
    when 'past'
      'alt'
    else 'next'
      'plus'
    end
  end

end

app/helpers/accounting/transactions_helper.rb
module Accounting::TransactionsHelper
end

app/helpers/accounting_helper.rb
module AccountingHelper
end

app/views/accounting/transactions/_form.html.erb
<%= form_with(model: accounting_transaction, local: true, html: {class:'user'}) do |form| %>
  <% if accounting_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(accounting_transaction.errors.count, "error") %> prohibited this accounting_transaction from being saved:</h2>
      <ul>
        <% accounting_transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='form-group'>
    <%= form.label :event_id, 'Evento' %>
    <%= form.select :event_id, Accounting::Event.all.collect{|p| [ p.name, p.id ] }, { include_blank: 'Selecciona un evento' }, { class:'form-control' } %>
  </div>
    <div class='form-group'>
    <%= form.label :account_id, 'Cuenta' %>
    <%= form.select :account_id, Accounting::Account.all.collect{|p| [ p.name, p.id ] }, { include_blank: 'Selecciona una cuenta' }, { class:'form-control' } %>
  </div>
  <div class='form-group'>
    <%= form.label :date, 'Fecha' %>
    <%= form.date_field :date, class:'form-control form-control-user' %>
  </div>
  <div class='form-group'>
    <%= form.label :type_of_transaction, 'Tipo de Transacción' %>
    <%= form.select :type_of_transaction, [['Ingreso', 0], ['Egreso', 1]], { include_blank: 'Selecciona el Tipo' }, { class:'form-control' } %>
    <small class='form-text text-muted text-xs'>Ingreso es cuando entra dinero al club, ej: Ventas de dulces. <br/>Egreso cuando el dinero sale del club, ej: Compra de dulces para ventas</small>
  </div>
  <div class='form-group'>
    <%= form.label :amount, 'Monto' %>
    <%= form.number_field :amount, class:'form-control form-control-user', min: 0, step: '0.01' %>
  </div>
  <div class='form-group'>
    <%= form.label :comments, 'Comentarios' %>
    <%= form.text_area :amount, class:'form-control form-control-user' %>
  </div>
  <%= form.submit class: "btn btn-primary btn-user btn-block", value: submit %>
<% end %>

app/views/accounting/transactions/edit.html.erb
<h1>Editing Accounting Transaction</h1>

<%= render 'form', accounting_transaction: @accounting_transaction %>

<%= link_to 'Show', @accounting_transaction %> |
<%= link_to 'Back', accounting_transactions_path %>
<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-2">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-event-form-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Editar Transacción</h1>
                </div>
                <%= render 'form', accounting_transaction: @accounting_transaction, submit: 'Editar Transacción' %>
                <hr>
                <div class='my-1 text-center'>
                  <%= link_to 'Ver Evento', @accounting_transaction, class: 'btn btn-info' %>
                  <%= link_to 'Volver', accounting_transactions_path, class: 'btn btn-danger' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounting/transactions/index.html.erb
<div class='d-flex justify-content-between'>
  <h1 class='h3 mb-0 text-gray-800'>
    Transacciones
  </h1>
  <%= link_to new_accounting_transaction_path, class:'text-info' do %>
    <i class="fas fa-plus fa-2x"></i>
  <% end %>
</div>
<hr>

<div class="row mb-5">
  <div class="col-12 mx-auto">
    <div class="card shadow">
      <div class="card-body">
        <table class="table">
          <thead>
            <tr>
              <th>Fecha</th>
              <th>Evento</th>
              <th>Cuenta</th>
              <th>Tipo</th>
              <th>Monto</th>
              <th colspan="2">Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @accounting_transactions.each do |t| %>
              <tr>
                <td><%= t.date %></td>
                <td><%= t.event.try(:name).blank? ? 'Global' : t.event.name %></td>
                <td><%= t.account.name %></td>
                <td><%= t.type_of_transaction %></td>
                <td><%= number_to_currency t.amount %></td>
                <td colspan="2">
                  <%= link_to accounting_transaction_path(t), class: 'text-info' do%>
                    <i class="fas fa-search"></i>
                  <% end %>
                  <%= link_to t, method: :delete, data: { confirm: 'Are you sure?' }, class:'text-danger' do%>
                    <i class="far fa-trash-alt"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/accounting/transactions/new.html.erb
<div class="container">
  <!-- Outer Row -->
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-2">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-event-form-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Crear Transacción</h1>
                </div>
                <%= render 'form', accounting_transaction: @accounting_transaction, submit: 'Crear Transacción' %>
                <hr>
                <%= link_to 'Volver', accounting_transactions_path, class: 'btn btn-secondary btn-block' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounting/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_accounting_transaction_path(@accounting_transaction) %> |
<%= link_to 'Back', accounting_transactions_path %>