config/routes.rb
Rails.application.routes.draw do

  namespace :accounting do
  end
  namespace :accounting do
  end
  namespace :accounting do
    resources :accounts
    resources :transactions
    resources :events
    resources :entry_lines, only: [:index, :show]
    resources :entries, only: [:index, :show]


    
  end
  get '/accounting', to: 'accounting#show'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  root 'pages#home'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  } 
  resources :users, only: [:index, :edit, :update, :delete]

  get 'profile', action: :show, controller: 'users'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/accounting.rb
module Accounting
  def self.table_name_prefix
    'accounting_'
  end
end

app/models/accounting/account.rb
class Accounting::Account < ApplicationRecord
  has_many :transactions

  after_create :create_initial_transaction

  def create_initial_transaction
    self.transactions.create(date: self.created_at, type_of_transaction: 2, amount: self.initial_balance.to_f, comments: 'New account!')
  end

  def balance 
    self.transactions.reduce(self.initial_balance.to_f) {|amount, num| num.try(:type_of_transaction) == 0 ? amount + num.amount : num.try(:type_of_transaction) == 1 ? amount - num.amount : amount + 0}
  end
end

app/models/accounting/entry.rb
class Accounting::Entry < ApplicationRecord
  belongs_to :movement, foreign_key: :transaction_id, class_name: 'Transaction'

  has_many :entry_lines

  after_create :create_lines

  def create_lines
    ## Select the type of transaction
    case self.movement.type_of_transaction
    when 0
      self.update(description: 'Sale')
      income = self.movement.amount*-1
      account = self.movement.amount
    when 1
      self.update(description: 'Purchase')
      outcome = self.movement.amount
      account = self.movement.amount*-1
    when 2
      self.update(description: 'New Account')
      account = self.movement.amount
      capital = self.movement.amount*-1
    when 3
      self.update(description: 'Destroy Account')
      account = self.movement.amount*-1
      capital = self.movement.amount
    end
    ## Make a hash to sort the lines
    lines = {
      'capital' => ['3001', capital],
      'account' => ["10#{self.movement.account.id}", account],
      'income' => ['4001', income],
      'outcome' => ['5001', outcome] 
    }.reject {|k, v| v[1].blank? or v[1] == 0}

    ## Create lines
    lines.each do |name, values|
      debit = values[1] > 0 ? values[1] : 0
      credit = values[1] < 0 ? values[1] : 0
      self.entry_lines.create(account_number: values[0], credit: credit, debit: debit)
    end
  end
end

app/models/accounting/entry_line.rb
class Accounting::EntryLine < ApplicationRecord
  belongs_to :entry, foreign_key: :entry_id

end

app/models/accounting/event.rb
class Accounting::Event < ApplicationRecord
  has_many :transactions
  def status
    case true
    when (self.start_date .. self.end_date).cover?(Date.today)
      'active'
    when Date.today < self.start_date
      'next'
    when Date.today > self.end_date
      'past'
    end
    
  end

end

app/models/accounting/transaction.rb
class Accounting::Transaction < ApplicationRecord
  belongs_to :event, foreign_key: :event_id, optional: true
  belongs_to :account, foreign_key: :account_id

  has_one :entry

  after_create :make_entry

  def make_entry
    self.create_entry(date: self.date)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  include Gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  gravtastic

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end
end

app/controllers/accounting_controller.rb
class AccountingController < ApplicationController
  def show

    respond_to do |f|
      f.html {render 'pages/accounting'}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def after_sign_in_path_for(resource)
    profile_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: :home
  def home
  end

  def dashboard
    authorize :dashboard, :show?
    @dashboard = true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_dashboard

  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_dashboard
    @dashboard = true
  end

end

app/helpers/accounting/accounts_helper.rb
module Accounting::AccountsHelper

  def get_balance_color(balance)
    case balance
    when -Float::INFINITY...0
      'danger'
    when 0
      'warning'
    else 
      'success'
    end
  end

  def get_balance_icon(balance)
    case balance
    when -Float::INFINITY...0
      'skull-crossbones'
    when 0
      'exclamation'
    else 
      'check'
    end
  end
end

app/helpers/accounting/entries_helper.rb
module Accounting::EntriesHelper
end

app/helpers/accounting/events_helper.rb
module Accounting::EventsHelper
  def get_status_color(status)
    case status
    when 'active'
      'success'
    when 'past'
      'dark'
    else 'next'
      'warning'
    end
  end

  def get_status_icon(status)
    case status
    when 'active'
      'check'
    when 'past'
      'alt'
    else 'next'
      'plus'
    end
  end

end

app/helpers/accounting_helper.rb
module AccountingHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alerts.html.erb
<% if notice || alert %>
  <div class="container my-3">
    <% if notice %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class='navbar navbar-expand-lg navbar-light bg-primary shadow mb-3' >
  <div class='container'>
    <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarTogglerDemo02' aria-controls='navbarTogglerDemo02' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>
    <div class='collapse navbar-collapse' id='navbarTogglerDemo02'>
      <ul class='navbar-nav ml-auto mt-2 mt-lg-0 d-flex align-items-center'>
     
        <li class="nav-item dropdown">
          <a class='dropdown-toggle nav-link' href="javascript.void(0)" id="scripts_menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="la la-cogs"></i></i> Scripts
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="scripts_menu">
            <%= link_to 'Cuentas', accounting_path, class: 'dropdown-item'%>
          </div>
        </li>

        <% if current_user %>
          <% if policy(:dashboard).show? %>
            <li class="nav-item">
              <%= link_to dashboard_path, class: 'nav-link' do %>
                <i class="las la-tachometer-alt"></i> Dashboard
              <% end %> 
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
              <i class="la la-user-minus"></i> Cerrar Sesión
            <% end %>
          </li> 
          <li class="nav-item ">
            <%= link_to profile_path, class: 'nav-link' do %>
              <%= current_user.name %>
              <%= image_tag current_user.gravatar_url, :width => 16 %>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: 'nav-link' do %>
            <i class="la la-user"></i> Ingresar
            <% end %>
          </li> 
          <li class="nav-item">
            <%= link_to  new_user_registration_path, class: 'nav-link  text-gray' do %>
              <i class="las la-user-plus"></i> Registrarse
            <% end %>
          </li> 
        <% end %> 
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-secondary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
    <div class="sidebar-brand-icon">
         <img src=<%= asset_path("profile.png") %> width='30' height='30' class='d-inline-block align-top' loading='lazy' />
        
    </div>
    <div class="sidebar-brand-text mx-1">Gestión CDUP<sup>2</sup></div>
  </a>

  <!-- Divider -->

  <!-- Nav Item - Dashboard -->
  <li class="nav-item">
    <a class="nav-link" href="/dashboard">
      <i class="las la-tachometer-alt text-white"></i>
      <span>Dashboard</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading text-primary">
    Scripts
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link" href="#" data-toggle="collapse" data-target="#events_menu_sidebar" aria-expanded="false" aria-controls="events_menu_sidebar">
      <i class="las la-calendar text-white"></i>
      <span>Cuentas</span>
    </a>
    <div id="events_menu_sidebar" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar" >
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Eventos</h6>
        <%= link_to  "Ver todos", accounting_events_path, class: 'collapse-item' %>
        <%= link_to "Crear Nuevo Evento", new_accounting_event_path, class: 'collapse-item' %>
        <h6 class="collapse-header">Transacciones</h6>
        <%= link_to  "Ver todas", accounting_transactions_path, class: 'collapse-item' %>
        <%= link_to "Crear nueva transacción", new_accounting_transaction_path, class: 'collapse-item' %>
        <h6 class="collapse-header">Cuentas</h6>
        <%= link_to  "Ver todas", accounting_accounts_path, class: 'collapse-item' %>
        <%= link_to "Crear nueva Cuenta", new_accounting_account_path, class: 'collapse-item' %>
        <h6 class="collapse-header">Diario</h6>
        <%= link_to  "Asientos", accounting_entries_path, class: 'collapse-item' %>
        <%= link_to  "Registros", accounting_entry_lines_path, class: 'collapse-item' %>
      </div>
    </div>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle">
      <i class="fas fa-chevron-left text-white"></i>
    </button>
  </div>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CDUP || Gestor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel='stylesheet' href='https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css'>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <div id="wrapper">
      <%= yield %>   
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CDUP || Gestor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel='stylesheet' href='https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css'>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <%= stylesheet_pack_tag 'dashboard', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'sb-admin-2', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="wrapper">
      <%= render 'layouts/sidebar' %>
      <div id="content_wrapper" class="d-flex flex-column w-100">
        <%= render 'layouts/navbar' %>
        <%= render 'layouts/alerts' %>
        <div class='container'>
          <div class='row justify-content-center'>
            <div class='col-xl-10 col-lg-12 col-md-9 pt-1'>
            <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
    
  </body>
</html>

app/views/pages/accounting.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    Gestor de CDUP
  </h1> 
  <p>
    Hola
  </p> 
  <div class="list-group">
    <a href='/' class="list-group-item list-group-item-action"> Home</a>
  </div>
</div>

app/views/pages/dashboard.html.erb
Dashboard <i class='fa fa-bong'></i>

app/views/pages/home.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#download">Download</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#features">Features</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100">
        <div class="col-lg-7 my-auto">
          <div class="header-content mx-auto">
            <h1 class="mb-5">New Age is an app landing page that will help you beautifully showcase your new mobile app, or anything else!</h1>
            <a href="#download" class="btn btn-outline btn-xl js-scroll-trigger">Start Now for Free!</a>
          </div>
        </div>
        <div class="col-lg-5 my-auto">
          <div class="device-container">
            <div class="device-mockup iphone6_plus portrait white">
              <div class="device">
                <div class="screen">
                  <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                  <img src="img/demo-screen-1.jpg" class="img-fluid" alt="">
                </div>
                <div class="button">
                  <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

  <section class="download bg-primary text-center" id="download">
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <h2 class="section-heading">Discover what all the buzz is about!</h2>
          <p>Our app is available on any mobile device! Download now to get started!</p>
          <div class="badges">
            <a class="badge-link" href="#"><img src="img/google-play-badge.svg" alt=""></a>
            <a class="badge-link" href="#"><img src="img/app-store-badge.svg" alt=""></a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="features" id="features">
    <div class="container">
      <div class="section-heading text-center">
        <h2>Unlimited Features, Unlimited Fun</h2>
        <p class="text-muted">Check out what you can do with this app theme!</p>
        <hr>
      </div>
      <div class="row">
        <div class="col-lg-4 my-auto">
          <div class="device-container">
            <div class="device-mockup iphone6_plus portrait white">
              <div class="device">
                <div class="screen">
                  <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                  <img src="img/demo-screen-1.jpg" class="img-fluid" alt="">
                </div>
                <div class="button">
                  <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-8 my-auto">
          <div class="container-fluid">
            <div class="row">
              <div class="col-lg-6">
                <div class="feature-item">
                  <i class="icon-screen-smartphone text-primary"></i>
                  <h3>Device Mockups</h3>
                  <p class="text-muted">Ready to use HTML/CSS device mockups, no Photoshop required!</p>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="feature-item">
                  <i class="icon-camera text-primary"></i>
                  <h3>Flexible Use</h3>
                  <p class="text-muted">Put an image, video, animation, or anything else in the screen!</p>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-6">
                <div class="feature-item">
                  <i class="icon-present text-primary"></i>
                  <h3>Free to Use</h3>
                  <p class="text-muted">As always, this theme is free to download and use for any purpose!</p>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="feature-item">
                  <i class="icon-lock-open text-primary"></i>
                  <h3>Open Source</h3>
                  <p class="text-muted">Since this theme is MIT licensed, you can use it commercially!</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="cta">
    <div class="cta-content">
      <div class="container">
        <h2>Stop waiting.<br>Start building.</h2>
        <a href="#contact" class="btn btn-outline btn-xl js-scroll-trigger">Let's Get Started!</a>
      </div>
    </div>
    <div class="overlay"></div>
  </section>

  <section class="contact bg-primary" id="contact">
    <div class="container">
      <h2>We
        <i class="fas fa-heart"></i>
        new friends!</h2>
      <ul class="list-inline list-social">
        <li class="list-inline-item social-twitter">
          <a href="#">
            <i class="fab fa-twitter"></i>
          </a>
        </li>
        <li class="list-inline-item social-facebook">
          <a href="#">
            <i class="fab fa-facebook-f"></i>
          </a>
        </li>
        <li class="list-inline-item social-google-plus">
          <a href="#">
            <i class="fab fa-google-plus-g"></i>
          </a>
        </li>
      </ul>
    </div>
  </section>

  <footer>
    <div class="container">
      <p>&copy; Your Website 2019. All Rights Reserved.</p>
      <ul class="list-inline">
        <li class="list-inline-item">
          <a href="#">Privacy</a>
        </li>
        <li class="list-inline-item">
          <a href="#">Terms</a>
        </li>
        <li class="list-inline-item">
          <a href="#">FAQ</a>
        </li>
      </ul>
    </div>
  </footer>